<?php

namespace App\Controllers;
use App\Core\Attributes\Route;
use App\Core\Controller;
use App\Core\Responce;

class NewsController extends Controller
{
    /**
     * @return ?string
     */
    public function list(): ?string
    {
        return $this->render(['title'=>'text','text'=>'mytext']);
    }

    #[Route("addition")]
    /**
     * @return Responce
     */
    public function add(): Responce
    {
        return new Responce("ADD", "TEXT");
    }

    #[Route("home")]
    /**
     * @return Responce
     */
    public function index(): Responce
    {
        return new Responce("INDEX", "TEXT");
    }
    public function render(array $assoc_array): string
    {
        $assoc_array['module']='news';
        return parent::render($assoc_array); // TODO: Change the autogenerated stub
    }
}